name = "karystore"
main = "worker.js"
compatibility_date = "2026-07-03"

[assets]
directory = "./"
binding = "ASSETS"
run_worker_first = ["/", "/index.html", "/api/*"]

kv_namespaces = [
  { binding = "STORE_KV", id = "0fdabb9050184676ac74e58fc8e60fd4" }
]

# ADMIN_HASH بيتضاف كـ Secret من Settings -> Variables and secrets في الداشبورد
